[project]
name = "scrape_squad"
version = "0.1.0"
description = "scrape_squad using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.76.9,<1.0.0"
]

[project.scripts]
scrape_squad = "scrape_squad.main:run"
run_crew = "scrape_squad.main:run"
train = "scrape_squad.main:train"
replay = "scrape_squad.main:replay"
test = "scrape_squad.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
