export const REMOTE_RESOURCES = [
  'https://www.ufos.wiki/',
  'https://anomalien.com',
  'https://enigmalabs.io/',
  'https://www.ufoexplorations.com/',
  'https://www.anomalist.com/',
  'https://anomalyarchives.org/',
  'https://www.theblackvault.com/documentarchive/category/the-fringe/ufo-phenomena/',
  'https://www.cia.gov/readingroom/search/site?f%5B0%5D=im_field_taxonomy_keyword%3A477',
  'https://vault.fbi.gov/UFO/',
  'https://www.nsa.gov/Helpful-Links/NSA-FOIA/Frequently-Requested-Information/Unidentified-Flying-Objects-UFOs/',
  'https://www.history.com/news/ufo-sightings-credible-modern',
  'https://inplainsight-book.com/',
  'https://www.thinkaboutitdocs.com/',
  'https://nufohrc.org/',
  'https://drive.google.com/drive/folders/1rgRvJf2qwDypmFaMa67s2405qyMbUe__',
]
