export const REMOTE_RESOURCES = [
  'https://www.ufos.wiki/',
  'https://anomalien.com',
  'https://enigmalabs.io/',
  'https://www.ufoexplorations.com/',
  'https://www.anomalist.com/',
  'https://anomalyarchives.org/',
  'https://www.theblackvault.com/documentarchive/category/the-fringe/ufo-phenomena/',
  'https://www.cia.gov/readingroom/search/site?f%5B0%5D=im_field_taxonomy_keyword%3A477',
  'https://vault.fbi.gov/UFO/',
  'https://www.nsa.gov/Helpful-Links/NSA-FOIA/Frequently-Requested-Information/Unidentified-Flying-Objects-UFOs/',
  'https://www.history.com/news/ufo-sightings-credible-modern',
  'https://inplainsight-book.com/',
  'https://www.thinkaboutitdocs.com/',
  'https://nufohrc.org/',
  'https://drive.google.com/drive/folders/1rgRvJf2qwDypmFaMa67s2405qyMbUe__',
  'https://www.mufog.co.uk/',
  'https://uapswiki.wpenginepowered.com/links/',
]

// https://www.thinkaboutitdocs.com/2000-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-june-july-ufo-aliens-sightings/
// https://www.thinkaboutitdocs.com/2000-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2000-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2001-sightings/
// https://www.thinkaboutitdocs.com/2001-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-febuary-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2001-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2002-sightings/
// https://www.thinkaboutitdocs.com/2002-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2002-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2003-sightings/
// https://www.thinkaboutitdocs.com/2003-january-march-sightings/
// https://www.thinkaboutitdocs.com/2003-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2003-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2003-april-ufo-aliens-sightings/
// https://www.thinkaboutitdocs.com/2003-may-ufo-aliens-sightings/
// https://www.thinkaboutitdocs.com/2003-june-ufo-aliens-sightings/
// https://www.thinkaboutitdocs.com/2003-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2003august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2003-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2003-october-ufo-alien-sighting/
// https://www.thinkaboutitdocs.com/2003-november-ufo-alien-sighting/
// https://www.thinkaboutitdocs.com/2003-december-ufo-alien-sighting/
// https://www.thinkaboutitdocs.com/2003-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2004-sightings/
// https://www.thinkaboutitdocs.com/2004-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-march-may-sightings/
// https://www.thinkaboutitdocs.com/2004-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2004-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2005-sightings/
// https://www.thinkaboutitdocs.com/2005-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2005-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2006-sightings/
// https://www.thinkaboutitdocs.com/2006-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-febuary-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2006-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2007-sightings/
// https://www.thinkaboutitdocs.com/2007-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2007-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2008-sightings/
// https://www.thinkaboutitdocs.com/2008-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-february-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2008-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2009-sightings/
// https://www.thinkaboutitdocs.com/2009-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-may-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2009-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2010-sightings/
// https://www.thinkaboutitdocs.com/2010-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-october-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2010-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2011-sightings/
// https://www.thinkaboutitdocs.com/2011-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-october-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2011-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2012-sightings/
// https://www.thinkaboutitdocs.com/2012-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2012-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2013-sightings/
// https://www.thinkaboutitdocs.com/2013-january-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2013-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2013-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2013-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2013-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2013-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2013-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2014-sightings/
// https://www.thinkaboutitdocs.com/2014-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2014-unknown-date-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2015-sightings/
// https://www.thinkaboutitdocs.com/2015-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-febuary-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-june-sightings/
// https://www.thinkaboutitdocs.com/2015-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2015-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2016-sightings/
// https://www.thinkaboutitdocs.com/2016-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2016-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2017-sightings/
// https://www.thinkaboutitdocs.com/2017-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-may-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-june-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-august-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-september-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-october-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-november-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2017-december-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/category/sightings-by-date/2000-present-sightings/2018-sightings/
// https://www.thinkaboutitdocs.com/2018-january-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2018-february-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2018-march-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2018-april-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2018-july-ufo-alien-sightings/
// https://www.thinkaboutitdocs.com/2018-august-ufo-alien-sightings/
