// import { sql } from '@vercel/postgres'

// import { drizzle } from 'drizzle-orm/vercel-postgres'

// import {
//   pgTable,
//   serial,
//   text,
//   timestamp,
//   uniqueIndex,
// } from 'drizzle-orm/pg-core'

// // Use this object to send drizzle queries to your DB
// export const db = drizzle( sql )
// // Create a pgTable that maps to a table in your DB
// export const ExampleTable = pgTable(
//   'users',
//   {
//     id: serial( 'id' ).primaryKey(),
//     name: text( 'name' ).notNull(),
//     email: text( 'email' ).notNull(),
//     image: text( 'image' ).notNull(),
//     createdAt: timestamp( 'createdAt' ).defaultNow().notNull(),
//   },
//   ( users ) => {
//     return {
//       uniqueIdx: uniqueIndex( 'unique_idx' ).on( users.email ),
//     }
//   },
// )

// export const getExampleTable = async () => {
//   const selectResult = await db.select().from( ExampleTable )
//   console.log( 'Results', selectResult )
// }
// import "dotenv/config"
// import { dbInserts } from '@/lib/db-inserts'



// export async function seed() {
//   const createTable = await sql`
    
// CREATE TABLE documents (
//     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     content text,
//     metadata jsonb,
//     embedding vector(1536)
    
// );

// CREATE TABLE events (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     name varchar,
//     location varchar,
//     date date,
//     latitude real,
//     longitude real,
//     description text,
//     photos jsonb
    
// );

// CREATE TABLE organizations (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     name varchar,
//     specialization varchar,
//     description text,
//     photo text,
//     image text,
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE key_figures (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     name varchar,
//     bio text,
//     role varchar,
//     facebook varchar,
//     twitter varchar,
//     website varchar,
//     instagram varchar,
//     rank integer,
//     photo jsonb,
//     credibility integer,
//     popularity integer,
//     authority integer,
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE topics (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     name varchar,
//     summary text,
//     photo text,
//     photos jsonb,
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE testimonies (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     claim text,
//     summary text,
//     documentation jsonb,
//     event_id integer REFERENCES events(id),
//     date timestamp without time zone,
//     witness_id integer REFERENCES key_figures(id),
//     organization_id integer REFERENCES organizations(id),
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE sightings (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     date timestamp with time zone,
//     description text,
//     media_link text,
//     city varchar,
//     state varchar,
//     country varchar,
//     shape varchar,
//     duration_seconds varchar,
//     duration_hours_min varchar,
//     comments text,
//     date_posted date,
//     latitude numeric,
//     longitude numeric
    
// );

// CREATE TABLE artifacts (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     name text NOT NULL,
//     description text,
//     photos text[],
//     date text,
//     source text,
//     origin text,
//     images text[]
    
// );

// CREATE TABLE users (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     email text NOT NULL,
//     name text NOT NULL,
//     photo text,
//     profile_image_url text,
//     external_id text
    
// );


// CREATE TABLE organization_members (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     member_id integer REFERENCES key_figures(id),
//     organization_id integer REFERENCES organizations(id),
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE topic_subject_matter_experts (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     topic_id integer REFERENCES topics(id),
//     subject_matter_expert_id integer REFERENCES key_figures(id),
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE event_subject_matter_experts (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     event_id integer REFERENCES events(id),
//     subject_matter_expert_id integer REFERENCES key_figures(id),
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE topics_testimonies (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     topic_id integer REFERENCES topics(id),
//     testimony_id integer REFERENCES testimonies(id),
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );

// CREATE TABLE event_topic_subject_matter_experts (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     event_id integer REFERENCES events(id),
//     topic_id integer REFERENCES topics(id),
//     subject_matter_expert_id integer REFERENCES key_figures(id),
//     created_at timestamp without time zone,
//     updated_at timestamp without time zone,
//     version integer
    
// );


// CREATE TABLE user_theories (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     user_id integer REFERENCES users(id),
//     title text NOT NULL,
//     content text,
//     synopsis text,
//     diagrams text[],
//     description text
// );

// CREATE TABLE user_saved_events (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     user_id integer REFERENCES users(id),
//     event_id integer REFERENCES events(id),
//     note text,
//     note_title text
    
// );

// CREATE TABLE user_saved_topics (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     user_id integer REFERENCES users(id),
//     topic_id integer REFERENCES topics(id),
//     note text,
//     note_title text
    
// );

// CREATE TABLE user_saved_documents (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     user_id integer REFERENCES users(id),
//     document_id integer REFERENCES documents(id),
//     note text,
//     note_title text
    
// );

// CREATE TABLE user_saved_testimonies (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     user_id integer REFERENCES users(id),
//     testimony_id integer REFERENCES testimonies(id),
//     note text,
//     note_title text
    
// );

// CREATE TABLE user_saved_organizations (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     user_id integer REFERENCES users(id),
//     organization_id integer REFERENCES organizations(id),
//     note text,
//     note_title text
    
// );

// CREATE TABLE mindmaps (
//     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//     xata_id varchar,
//     json json DEFAULT '{}'::json,
//     embedding vector(1536),
//     user_id integer REFERENCES users(id),
//     file text
    
// );


// ALTER TABLE ONLY public.documents
//     ADD CONSTRAINT documents_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.event_subject_matter_experts
//     ADD CONSTRAINT event_subject_matter_experts_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.event_subject_matter_experts
//     ADD CONSTRAINT event_subject_matter_experts_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.event_topic_subject_matter_experts
//     ADD CONSTRAINT event_topic_subject_matter_experts_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.event_topic_subject_matter_experts
//     ADD CONSTRAINT event_topic_subject_matter_experts_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.events
//     ADD CONSTRAINT events_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.events
//     ADD CONSTRAINT events_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.key_figures
//     ADD CONSTRAINT key_figures_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.key_figures
//     ADD CONSTRAINT key_figures_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.organization_members
//     ADD CONSTRAINT organization_members_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.organization_members
//     ADD CONSTRAINT organization_members_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.organizations
//     ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.organizations
//     ADD CONSTRAINT organizations_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.testimonies
//     ADD CONSTRAINT testimonies_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.testimonies
//     ADD CONSTRAINT testimonies_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.testimonies_xata
//     ADD CONSTRAINT testimonies_xata_pkey PRIMARY KEY (xata_id);



// ALTER TABLE ONLY public.theories
//     ADD CONSTRAINT theories_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.topic_subject_matter_experts
//     ADD CONSTRAINT topic_subject_matter_experts_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.topic_subject_matter_experts
//     ADD CONSTRAINT topic_subject_matter_experts_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.topics
//     ADD CONSTRAINT topics_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.topics_testimonies
//     ADD CONSTRAINT topics_testimonies_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.topics_testimonies
//     ADD CONSTRAINT topics_testimonies_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.topics
//     ADD CONSTRAINT topics_xata_id_key UNIQUE (xata_id);



// ALTER TABLE ONLY public.user_saved_documents
//     ADD CONSTRAINT user_saved_documents_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.user_saved_events
//     ADD CONSTRAINT user_saved_events_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.user_saved_organizations
//     ADD CONSTRAINT user_saved_organizations_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.user_saved_testimonies
//     ADD CONSTRAINT user_saved_testimonies_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.user_saved_topics
//     ADD CONSTRAINT user_saved_topics_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.user_theories
//     ADD CONSTRAINT user_theories_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.users
//     ADD CONSTRAINT users_email_key UNIQUE (email);



// ALTER TABLE ONLY public.users
//     ADD CONSTRAINT users_pkey PRIMARY KEY (id);



// ALTER TABLE ONLY public.xata_to_postgres_mapping
//     ADD CONSTRAINT xata_to_postgres_mapping_pkey PRIMARY KEY (xata_id);



// CREATE INDEX user_theories_user_id_name_key ON public.user_theories USING btree (user_id, title);



// ALTER TABLE ONLY public.event_subject_matter_experts
//     ADD CONSTRAINT event_subject_matter_experts_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);



// ALTER TABLE ONLY public.event_subject_matter_experts
//     ADD CONSTRAINT event_subject_matter_experts_subject_matter_expert_id_fkey FOREIGN KEY (subject_matter_expert_id) REFERENCES public.key_figures(id);



// ALTER TABLE ONLY public.event_topic_subject_matter_experts
//     ADD CONSTRAINT event_topic_subject_matter_expert_subject_matter_expert_id_fkey FOREIGN KEY (subject_matter_expert_id) REFERENCES public.key_figures(id);



// ALTER TABLE ONLY public.event_topic_subject_matter_experts
//     ADD CONSTRAINT event_topic_subject_matter_experts_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);



// ALTER TABLE ONLY public.event_topic_subject_matter_experts
//     ADD CONSTRAINT event_topic_subject_matter_experts_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id);



// ALTER TABLE ONLY public.organization_members
//     ADD CONSTRAINT organization_members_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.key_figures(id);



// ALTER TABLE ONLY public.organization_members
//     ADD CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);



// ALTER TABLE ONLY public.testimonies
//     ADD CONSTRAINT testimonies_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);



// ALTER TABLE ONLY public.testimonies
//     ADD CONSTRAINT testimonies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);



// ALTER TABLE ONLY public.testimonies
//     ADD CONSTRAINT testimonies_witness_id_fkey FOREIGN KEY (witness_id) REFERENCES public.key_figures(id);



// ALTER TABLE ONLY public.topic_subject_matter_experts
//     ADD CONSTRAINT topic_subject_matter_experts_subject_matter_expert_id_fkey FOREIGN KEY (subject_matter_expert_id) REFERENCES public.key_figures(id);



// ALTER TABLE ONLY public.topic_subject_matter_experts
//     ADD CONSTRAINT topic_subject_matter_experts_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id);



// ALTER TABLE ONLY public.topics_testimonies
//     ADD CONSTRAINT topics_testimonies_testimony_id_fkey FOREIGN KEY (testimony_id) REFERENCES public.testimonies(id);



// ALTER TABLE ONLY public.topics_testimonies
//     ADD CONSTRAINT topics_testimonies_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id);



// ALTER TABLE ONLY public.user_saved_documents
//     ADD CONSTRAINT user_saved_documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;



// ALTER TABLE ONLY public.user_saved_events
//     ADD CONSTRAINT user_saved_events_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;



// ALTER TABLE ONLY public.user_saved_events
//     ADD CONSTRAINT user_saved_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;



// ALTER TABLE ONLY public.user_saved_organizations
//     ADD CONSTRAINT user_saved_organizations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE SET NULL;



// ALTER TABLE ONLY public.user_saved_organizations
//     ADD CONSTRAINT user_saved_organizations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;



// ALTER TABLE ONLY public.user_saved_testimonies
//     ADD CONSTRAINT user_saved_testimonies_testimony_id_fkey FOREIGN KEY (testimony_id) REFERENCES public.testimonies(id) ON DELETE SET NULL;



// ALTER TABLE ONLY public.user_saved_testimonies
//     ADD CONSTRAINT user_saved_testimonies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;



// ALTER TABLE ONLY public.user_saved_topics
//     ADD CONSTRAINT user_saved_topics_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;



// ALTER TABLE ONLY public.user_saved_topics
//     ADD CONSTRAINT user_saved_topics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;



// ALTER TABLE ONLY public.user_theories
//     ADD CONSTRAINT user_theories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;




//   `



//   const insertedRecords = await sql`
//    ${dbInserts}
//     `.then( () => console.log( 'done' ) )
//   // const results: any[] = [];
//   // const csvFilePath = path.join(process.cwd(), 'unicorns.csv');

//   // await new Promise((resolve, reject) => {
//   //   fs.createReadStream(csvFilePath)
//   //     .pipe(csv())
//   //     .on('data', (data) => results.push(data))
//   //     .on('end', resolve)
//   //     .on('error', reject);
//   // });

//   // for (const row of results) {
//   //   const formattedDate = parseDate(row['Date Joined']);

//   //   await sql`
//   //     INSERT INTO unicorns (company, valuation, date_joined, country, city, industry, select_investors)
//   //     VALUES (
//   //       ${row.Company},
//   //       ${parseFloat(row['Valuation ($B)'].replace('$', '').replace(',', ''))},
//   //       ${formattedDate},
//   //       ${row.Country},
//   //       ${row.City},
//   //       ${row.Industry},
//   //       ${row['Select Investors']}
//   //     )
//   //     ON CONFLICT (company) DO NOTHING;
//   //   `;
//   // }

//   // console.log(`Seeded ${results.length} unicorns`);

//   return {
//     createTable,
//     insertedRecords
//   }
// }


// seed().catch( console.error )